### ISSUE TITLE
error message in get_states_daily

### ISSUE THREAD

**Issue by jmweintraub** [aedobbyn/covid19us#17]
I'm getting a new error message when I try to use get_states_daily()
> US <- get_states_daily()
Error: missing value where TRUE/FALSE needed
> Calif <- get_states_daily(state = "CA")
Error: missing value where TRUE/FALSE needed

devtools::session_info()
─ Session info ────────────────
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       macOS Catalina 10.15.3      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2020-05-06                  

─ Packages ───────────────────────────────────────────────────────
 package     * version  date       lib source        
 assertthat    0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
 backports     1.1.6    2020-04-05 [1] CRAN (R 4.0.0)
 bitops        1.0-6    2013-08-17 [1] CRAN (R 4.0.0)
 callr         3.4.3    2020-03-28 [1] CRAN (R 4.0.0)
 cli           2.0.2    2020-02-28 [1] CRAN (R 4.0.0)
 colorspace    1.4-1    2019-03-18 [1] CRAN (R 4.0.0)
 crayon        1.3.4    2017-09-16 [1] CRAN (R 4.0.0)
 desc          1.2.0    2018-05-01 [1] CRAN (R 4.0.0)
 devtools      2.3.0    2020-04-10 [1] CRAN (R 4.0.0)
 digest        0.6.25   2020-02-23 [1] CRAN (R 4.0.0)
 dplyr       * 0.8.5    2020-03-07 [1] CRAN (R 4.0.0)
 ellipsis      0.3.0    2019-09-20 [1] CRAN (R 4.0.0)
 fansi         0.4.1    2020-01-08 [1] CRAN (R 4.0.0)
 fs            1.4.1    2020-04-04 [1] CRAN (R 4.0.0)
 generics      0.0.2    2018-11-29 [1] CRAN (R 4.0.0)
 ggplot2     * 3.3.0    2020-03-05 [1] CRAN (R 4.0.0)
 glue          1.4.0    2020-04-03 [1] CRAN (R 4.0.0)
 gtable        0.3.0    2019-03-25 [1] CRAN (R 4.0.0)
 lifecycle     0.2.0    2020-03-06 [1] CRAN (R 4.0.0)
 lubridate   * 1.7.8    2020-04-06 [1] CRAN (R 4.0.0)
 magrittr      1.5      2014-11-22 [1] CRAN (R 4.0.0)
 memoise       1.1.0    2017-04-21 [1] CRAN (R 4.0.0)
 munsell       0.5.0    2018-06-12 [1] CRAN (R 4.0.0)
 pillar        1.4.4    2020-05-05 [1] CRAN (R 4.0.0)
 pkgbuild      1.0.7    2020-04-25 [1] CRAN (R 4.0.0)
 pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
 pkgload       1.0.2    2018-10-29 [1] CRAN (R 4.0.0)
 prettyunits   1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
 processx      3.4.2    2020-02-09 [1] CRAN (R 4.0.0)
 ps            1.3.2    2020-02-13 [1] CRAN (R 4.0.0)
 purrr         0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
 R6            2.4.1    2019-11-12 [1] CRAN (R 4.0.0)
 Rcpp          1.0.4.6  2020-04-09 [1] CRAN (R 4.0.0)
 RCurl       * 1.98-1.2 2020-04-18 [1] CRAN (R 4.0.0)
 remotes       2.1.1    2020-02-15 [1] CRAN (R 4.0.0)
 rlang         0.4.6    2020-05-02 [1] CRAN (R 4.0.0)
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 4.0.0)
 rstudioapi    0.11     2020-02-07 [1] CRAN (R 4.0.0)
 scales        1.1.0    2019-11-18 [1] CRAN (R 4.0.0)
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
 testthat      2.3.2    2020-03-02 [1] CRAN (R 4.0.0)
 tibble        3.0.1    2020-04-20 [1] CRAN (R 4.0.0)
 tidyr       * 1.0.2    2020-01-24 [1] CRAN (R 4.0.0)
 tidyselect    1.0.0    2020-01-27 [1] CRAN (R 4.0.0)
 usethis       1.6.1    2020-04-29 [1] CRAN (R 4.0.0)
 vctrs         0.2.4    2020-03-10 [1] CRAN (R 4.0.0)
 withr         2.2.0    2020-04-20 [1] CRAN (R 4.0.0)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

**Comment by sxmorgan** [comment]
I was getting that error yesterday as well, but today got this one:

```r
covid19us::get_states_daily()
#> Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [covidtracking.com] Connection timed out after 10004 milliseconds
#> Request failed [ERROR]. Retrying in 1 seconds...
#> Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached: [covidtracking.com] Connection timed out after 10000 milliseconds
#> Request failed [ERROR]. Retrying in 1.5 seconds...
#> Error: Timeout was reached: [covidtracking.com] Connection timed out after 10000 milliseconds
#> # A tibble: 0 x 0
```


``` r
sessionInfo()
#> R version 3.6.1 (2019-07-05)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS High Sierra 10.13.6
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.1  magrittr_1.5    tools_3.6.1     htmltools_0.4.0
#>  [5] yaml_2.2.1      Rcpp_1.0.4      stringi_1.4.6   rmarkdown_2.1  
#>  [9] highr_0.8       knitr_1.28      stringr_1.4.0   xfun_0.13      
#> [13] digest_0.6.25   rlang_0.4.6     evaluate_0.14
```

<sup>Created on 2020-05-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavidHinchee** [comment]
I"m getting the same error with different syntax:

First:
> library(covid19us)
> ladata <- get_states_daily(state="LA")
Error: missing value where TRUE/FALSE needed
> head(ladata)
# A tibble: 0 x 0

Second, using example from the documentation:

> library(dplyr)
> library(ggplot2)
> library(covid19us)
> 
> #
> 
> (dat <- refresh_covid19us())
Error: missing value where TRUE/FALSE needed
Error: `cols` must select at least one column.
Run `rlang::last_error()` to see where the error occurred.

Thanks,

David Hinchee

**Comment by aedobbyn** [comment]
Hey all -- sorry for the delay. Email notifications were off for some reason.

Let me know if you're still having issues. The API was updated a few weeks ago which broke a few things. Those should be fixed in the latest version on both CRAN and GitHub.

``` r
library(covid19us)

get_states_daily()
#> # A tibble: 4,609 x 27
#>    date       state positive negative pending hospitalized_cu… hospitalized_cu…
#>    <date>     <chr>    <int>    <int>   <int>            <int>            <int>
#>  1 2020-05-26 AK         411    44553      NA               12               NA
#>  2 2020-05-26 AL       15396   178363      NA               NA             1671
#>  3 2020-05-26 AR        6180   105593      NA              107              617
#>  4 2020-05-26 AS           0      124      NA               NA               NA
#>  5 2020-05-26 AZ       16783   173948      NA              818             1988
#>  6 2020-05-26 CA       96733  1599663      NA             4404               NA
#>  7 2020-05-26 CO       24269   131742      NA              507             4128
#>  8 2020-05-26 CT       41303   184059      NA              694            12538
#>  9 2020-05-26 DC        8334    33721      NA              353               NA
#> 10 2020-05-26 DE        9066    45848      NA              201               NA
#> # … with 4,599 more rows, and 20 more variables: in_icu_currently <int>,
#> #   in_icu_cumulative <int>, on_ventilator_currently <int>,
#> #   on_ventilator_cumulative <int>, recovered <int>, data_quality_grade <chr>,
#> #   last_update <dttm>, hash <chr>, date_checked <dttm>, death <int>,
#> #   hospitalized <int>, total <int>, total_test_results <int>, fips <chr>,
#> #   death_increase <int>, hospitalized_increase <int>, negative_increase <int>,
#> #   positive_increase <int>, total_test_results_increase <int>,
#> #   request_datetime <dttm>

get_states_daily(state = "LA")
#> # A tibble: 81 x 27
#>    date       state positive negative pending hospitalized_cu… hospitalized_cu…
#>    <date>     <chr>    <int>    <int>   <int>            <int>            <int>
#>  1 2020-05-26 LA       38054   302972      NA              831               NA
#>  2 2020-05-25 LA       37809   293089      NA              847               NA
#>  3 2020-05-24 LA       37169   278867      NA              813               NA
#>  4 2020-05-23 LA       37040   277407      NA              836               NA
#>  5 2020-05-22 LA       36925   274883      NA              867               NA
#>  6 2020-05-21 LA       36504   268877      NA              884               NA
#>  7 2020-05-20 LA       35316   250654      NA              931               NA
#>  8 2020-05-19 LA       35038   243035      NA             1004               NA
#>  9 2020-05-18 LA       34709   235039      NA             1031               NA
#> 10 2020-05-17 LA       34432   230738      NA             1019               NA
#> # … with 71 more rows, and 20 more variables: in_icu_currently <int>,
#> #   in_icu_cumulative <int>, on_ventilator_currently <int>,
#> #   on_ventilator_cumulative <int>, recovered <int>, data_quality_grade <chr>,
#> #   last_update <dttm>, hash <chr>, date_checked <dttm>, death <int>,
#> #   hospitalized <int>, total <int>, total_test_results <int>, fips <chr>,
#> #   death_increase <int>, hospitalized_increase <int>, negative_increase <int>,
#> #   positive_increase <int>, total_test_results_increase <int>,
#> #   request_datetime <dttm>
```

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
